spring:
  port: 8080
  application:
    name: 'gateway'
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/example/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/example/**
        - id: event-service
          uri: http://localhost:8083
          predicates:
            - Path=/example/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  datasource:
    url: "jdbc:postgresql://localhost:5432/baribir_db"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
jwt:
  secret: ''
